# Generated by Django 2.0.5 on 2018-05-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryAddressDesignator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The full name of the designator', max_length=120)),
                ('abbreviation', models.CharField(help_text="The designator's abbreviation", max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='StreetName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The street name', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='StreetSuffix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The colloquial name for the suffix', max_length=120)),
                ('abbreviation', models.CharField(help_text='The standard abbreviation for this suffix', max_length=12)),
            ],
        ),
    ]
